% Generated by MATLAB(R) 9.8 (R2020a) and LTE Toolbox 3.3 (R2020a).
% Generated on: 17-Sep-2020 00:18:48

%% Generate Downlink RMC Waveform
% Downlink RMC configuration:
cfg = struct('RC', 'R.0', ...
    'DuplexMode', 'FDD', ...
    'NCellID', 0, ...
    'TotSubframes', 100, ...
    'NumCodewords', 1, ...
    'Windowing', 0, ...
    'AntennaPort', 1);

cfg.OCNGPDSCHEnable = 'Off';
cfg.OCNGPDCCHEnable = 'Off';
cfg.PDSCH.TxScheme = 'Port0';
cfg.PDSCH.RNTI = 1;
cfg.PDSCH.Rho = 0;
cfg.PDSCH.RVSeq = [0 1 2 3];
cfg.PDSCH.NHARQProcesses = 8;
cfg.PDSCH.PMISet = 1;
cfg = lteRMCDL(cfg);

% input bit source:
in = [1; 0; 0; 1];


% waveform generation:
[waveform, grid, cfg] = lteRMCDLTool(cfg, in);

Fs = cfg.SamplingRate; 								 % sample rate of waveform

%% Visualize Downlink RMC Waveform
% Time Scope
timeScope = dsp.TimeScope('SampleRate', Fs, ...
    'TimeSpanOverrunAction', 'Scroll', ...
    'TimeSpan', 7.8125e-06);
timeScope(waveform);
release(timeScope);

% Spectrum Analyzer
spectrum = dsp.SpectrumAnalyzer('SampleRate', Fs);
spectrum(waveform);
release(spectrum);


